apiVersion: apps/v1
kind: Deployment
metadata:
    name: devops-exercise
spec:
    selector:
        matchLabels:
            app: devops-exercise
    replicas: 2
    template:
        metadata:
            labels:
                app: devops-exercise
        spec:
            containers:
                - name: devops-exercise
                  # imagePullPolicy: Never
                  image: marcobfj/devops-exercise:master
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: devops-exercise
spec:
    type: NodePort
    selector:
        app: devops-exercise
    ports:
        - port: 8080
          targetPort: 8080