name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy_to_minikube:
    runs-on: ubuntu-latest
    name: Deploy to minikube
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A
      
      - name: Deploy to minikube
        run:
          kubectl apply -f kubernetes/deploy.yml && sleep 5
          
      - name: Test service URLs
        run: |
          minikube service list
          minikube service devops-exercise --url
          echo "------------------opening the service------------------"
          curl $(minikube service devops-exercise --url)        
