
name: Publish Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: actions/checkout@v2
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-exercise:$(date +%s) .

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-exercise:$(date +%s)
      